# Generated by Django 4.0.5 on 2022-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_executives'),
    ]

    operations = [
        migrations.AddField(
            model_name='executives',
            name='exec_pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
