# Generated by Django 4.0.5 on 2022-06-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_executives_exec_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executives',
            new_name='Executive',
        ),
    ]
