# Generated by Django 4.0.5 on 2022-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='cause_detail',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
