# Generated by Django 4.0.5 on 2022-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_cause_cause_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='cause_detail',
        ),
        migrations.AddField(
            model_name='cause',
            name='cause_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
