# Generated by Django 4.0.5 on 2022-06-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_cause_cause_detail_cause_cause_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
