# Generated by Django 4.0.5 on 2022-06-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_cause_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, null=True)),
                ('event_body', models.TextField(null=True)),
                ('event_date', models.CharField(max_length=200, null=True)),
                ('event_time', models.CharField(max_length=200, null=True)),
                ('event_location', models.CharField(max_length=200, null=True)),
                ('event_pic', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
        ),
    ]
