# Generated by Django 4.0.5 on 2022-06-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_join'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='JoinEvent',
        ),
    ]
